'use client';

import {
  Fragment,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ClipboardEvent,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import {
  formatCell,
  parseCell,
  toSessionTsv,
  type GridColumn,
  type Prescription,
} from '@tp/domain';
import { ExerciseCombobox, type ExerciseHit } from '@/components/library/exercise-combobox';
import { Button } from '@/components/ui/button';
import type { GridStore, RowChange } from './grid-store';
import { PastePanel } from './paste-panel';

export interface GridRow {
  id: string;
  blockId: string;
  version: number;
  exercise: { id: string; name: string };
  category: string | null;
  prescription: Prescription;
  notes: string | null;
  /** Value generated by a progression rule or template (changing it is an audited override). */
  derived: boolean;
  issues: string[];
}
export interface GridBlock {
  id: string;
  title: string | null;
  rows: GridRow[];
}

type Col = 'exercise' | 'category' | GridColumn | 'notes';
const COLS: { key: Col; label: string; title?: string; cls: string }[] = [
  { key: 'exercise', label: 'Ejercicio', cls: 'min-w-52 text-left' },
  { key: 'category', label: 'Cat.', title: 'Categoría del ejercicio', cls: 'w-28 text-left' },
  { key: 'sets', label: 'Series', cls: 'w-16' },
  {
    key: 'reps',
    label: 'Reps',
    title: 'Repeticiones (8 o 6-8), tiempo (30 s), distancia (20 m) o contactos',
    cls: 'w-20',
  },
  {
    key: 'load',
    label: 'Carga',
    title: 'kg (80), % de 1RM (75 %), RPE 8, «banda roja» o «PC» (peso corporal)',
    cls: 'w-24',
  },
  { key: 'rir', label: 'RIR', title: 'Repeticiones en reserva; no a la vez que RPE', cls: 'w-14' },
  { key: 'rpe', label: 'RPE', title: 'Esfuerzo percibido 1–10; no a la vez que RIR', cls: 'w-14' },
  { key: 'rest', label: 'Desc.', title: 'Descanso entre series: 90, 2:30, 2 min', cls: 'w-16' },
  {
    key: 'notes',
    label: 'Notas',
    title: 'Notas para el cliente: las ve en su app',
    cls: 'min-w-40 text-left',
  },
];
const FIRST_EDITABLE = 2;
const isPrescription = (c: Col): c is GridColumn =>
  c === 'sets' || c === 'reps' || c === 'load' || c === 'rir' || c === 'rpe' || c === 'rest';

function cellText(row: GridRow, col: Col): string {
  if (col === 'exercise') return row.exercise.name;
  if (col === 'category') return row.category ?? '';
  if (col === 'notes') return row.notes ?? '';
  return formatCell(col, row.prescription);
}

type Undo =
  | { kind: 'edit'; rowId: string; body: RowChange; label: string }
  | { kind: 'remove'; ids: string[]; label: string }
  | { kind: 'move'; rowId: string; direction: 'up' | 'down'; label: string };

type Notice = { tone: 'ok' | 'warn' | 'danger'; text: string } | null;

/**
 * The session table (docs/UX_FLOW.md §2.3): one row per exercise, spreadsheet-style editing.
 * Each cell is saved on its own with optimistic locking: if another trainer changed the row, the
 * change is not overwritten; the row is reloaded and the trainer is told what was not saved.
 * Where it saves is the `store`: a client's session or a template (grid-store.ts).
 */
export function SessionGrid({
  gridId,
  store,
  blocks: initialBlocks,
  editable,
  renderDetails,
}: {
  /** Unique id for the table's elements (help text, errors). */
  gridId: string;
  store: GridStore;
  blocks: GridBlock[];
  editable: boolean;
  /** Advanced options of a row (tempo, VBT, methods, alternatives…), shown on demand. */
  renderDetails?: (rowId: string) => ReactNode;
}) {
  const [blocks, setBlocks] = useState(initialBlocks);
  useEffect(() => setBlocks(initialBlocks), [initialBlocks]);
  const rows = useMemo(() => blocks.flatMap((b) => b.rows), [blocks]);
  const [active, setActive] = useState({ r: 0, c: FIRST_EDITABLE });
  const [editing, setEditing] = useState<{
    r: number;
    c: number;
    text: string;
    error?: string;
  } | null>(null);
  const editRef = useRef<typeof editing>(null);
  const setEdit = (v: typeof editing) => {
    editRef.current = v;
    setEditing(v);
  };
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [details, setDetails] = useState<string | null>(null);
  const [notice, setNotice] = useState<Notice>(null);
  const [cellError, setCellError] = useState<{ key: string; text: string } | null>(null);
  const [pasting, setPasting] = useState<string | null>(null);
  const [focusRow, setFocusRow] = useState<string | null>(null);
  const undo = useRef<Undo[]>([]);
  const queues = useRef(new Map<string, Promise<unknown>>());
  const cells = useRef(new Map<string, HTMLTableCellElement>());
  const wantFocus = useRef(false);
  const clickedFocused = useRef(false);
  const grid = useRef<HTMLTableElement>(null);

  const r = Math.min(active.r, Math.max(rows.length - 1, 0));
  const current = rows[r];
  const targets = () =>
    selected.size ? rows.filter((x) => selected.has(x.id)) : current ? [current] : [];

  // Keep the cursor on a row added or pasted a moment ago, once the refreshed data arrives.
  useEffect(() => {
    if (!focusRow) return;
    const i = rows.findIndex((x) => x.id === focusRow);
    if (i >= 0) {
      wantFocus.current = true;
      setActive({ r: i, c: FIRST_EDITABLE });
      setFocusRow(null);
    }
  }, [rows, focusRow]);

  useEffect(() => {
    if (!wantFocus.current || editing) return;
    wantFocus.current = false;
    cells.current.get(`${r}:${active.c}`)?.focus();
  }, [r, active.c, editing]);

  const patchLocal = (id: string, change: Partial<GridRow>) =>
    setBlocks((bs) =>
      bs.map((b) => ({
        ...b,
        rows: b.rows.map((x) => (x.id === id ? { ...x, ...change } : x)),
      })),
    );

  /** Saves one row change after the previous change of that row (never two at once). */
  function save(row: GridRow, body: RowChange, local: Partial<GridRow>, u?: Undo) {
    patchLocal(row.id, local);
    // The undo entry is available at once (Ctrl+Z right after Enter), and dropped if saving fails.
    if (u) undo.current.push(u);
    const run = async () => {
      const res = await store.saveRow(row, body);
      if (res.ok) {
        store.refresh();
        return true;
      }
      if (u) undo.current = undo.current.filter((x) => x !== u);
      patchLocal(row.id, {
        prescription: row.prescription,
        notes: row.notes,
        exercise: row.exercise,
      });
      if (res.conflict) {
        setNotice({
          tone: 'danger',
          text: `Otra persona ha cambiado «${row.exercise.name}» mientras editabas: no se ha guardado tu cambio para no pisar el suyo. La fila se ha recargado; revísala y vuelve a escribirlo.`,
        });
        store.refresh();
      } else {
        const msg = Object.values(res.details ?? {}).flat()[0] ?? res.message;
        setNotice({ tone: 'danger', text: `${row.exercise.name}: ${msg}` });
      }
      return false;
    };
    const next = (queues.current.get(row.id) ?? Promise.resolve()).then(run, run);
    queues.current.set(row.id, next);
    return next;
  }

  function move(dr: number, dc: number) {
    wantFocus.current = true;
    setActive((a) => ({
      r: Math.max(0, Math.min(rows.length - 1, a.r + dr)),
      c: Math.max(0, Math.min(COLS.length - 1, a.c + dc)),
    }));
  }

  function startEdit(ri: number, ci: number, text?: string) {
    const row = rows[ri];
    const col = COLS[ci]!.key;
    if (!editable || !row || col === 'category') return;
    setCellError(null);
    setEdit({ r: ri, c: ci, text: text ?? (col === 'exercise' ? '' : cellText(row, col)) });
  }

  /** Commits the cell being edited (once); `then` moves the cursor afterwards (Enter/Tab). */
  function commit(then?: [number, number]) {
    const ed = editRef.current;
    if (!ed) return;
    editRef.current = null;
    commitText(ed.r, ed.c, ed.text, then);
  }

  function commitText(ri: number, ci: number, text: string, then?: [number, number]) {
    const row = rows[ri];
    const col = COLS[ci]!.key;
    const finish = () => {
      setEdit(null);
      if (then) move(...then);
      else wantFocus.current = true;
    };
    if (!row) return finish();
    if (text.trim() === cellText(row, col).trim()) return finish();
    if (isPrescription(col)) {
      const res = parseCell(col, text, row.prescription);
      if (!res.ok) {
        setEdit({ r: ri, c: ci, text, error: res.error });
        setCellError({ key: `${row.id}:${col}`, text: res.error });
        return;
      }
      const next = { ...row.prescription, ...res.patch };
      const prev = Object.fromEntries(
        Object.keys(res.patch).map((k) => [k, row.prescription[k as keyof Prescription] ?? null]),
      );
      const hadRir = row.prescription.rirMin != null || row.prescription.rirMax != null;
      if (hadRir && next.rirMin == null && next.rpeTarget != null)
        setNotice({ tone: 'warn', text: 'Se ha quitado el RIR: usa RIR o RPE, no los dos.' });
      else if (row.prescription.rpeTarget != null && next.rpeTarget == null && next.rirMin != null)
        setNotice({ tone: 'warn', text: 'Se ha quitado el RPE: usa RIR o RPE, no los dos.' });
      else setNotice(null);
      void save(
        row,
        { prescription: res.patch },
        { prescription: next },
        {
          kind: 'edit',
          rowId: row.id,
          body: { prescription: prev },
          label: `${COLS[ci]!.label.toLowerCase()} de ${row.exercise.name}`,
        },
      );
    } else if (col === 'notes') {
      const notes = text.trim() || null;
      void save(
        row,
        { notesForClient: notes },
        { notes },
        {
          kind: 'edit',
          rowId: row.id,
          body: { notesForClient: row.notes },
          label: `notas de ${row.exercise.name}`,
        },
      );
    }
    setCellError(null);
    finish();
  }

  function changeExercise(row: GridRow, hit: ExerciseHit) {
    setEdit(null);
    wantFocus.current = true;
    if (hit.id === row.exercise.id) return;
    void save(
      row,
      { exerciseId: hit.id, exerciseName: hit.name },
      { exercise: hit, category: null },
      {
        kind: 'edit',
        rowId: row.id,
        body: { exerciseId: row.exercise.id, exerciseName: row.exercise.name },
        label: `ejercicio ${hit.name}`,
      },
    );
  }

  async function addExercise(hit: ExerciseHit) {
    const res = await store.addRows([
      { exerciseId: hit.id, exerciseName: hit.name, prescription: { sets: 3 } },
    ]);
    if (!res.ok) return setNotice({ tone: 'danger', text: res.message });
    undo.current.push({ kind: 'remove', ids: res.ids, label: `añadir ${hit.name}` });
    setFocusRow(res.ids[0]!);
    setNotice({ tone: 'ok', text: `${hit.name} añadido: escribe las series, reps y carga.` });
    store.refresh();
  }

  async function rowsAction(kind: 'duplicate' | 'delete') {
    const list = targets();
    if (!list.length) return;
    if (
      kind === 'delete' &&
      !confirm(
        list.length === 1
          ? `¿Quitar «${list[0]!.exercise.name}» de la sesión?`
          : `¿Quitar ${list.length} ejercicios de la sesión?`,
      )
    )
      return;
    const ids = list.map((x) => x.id);
    if (kind === 'duplicate') {
      const res = await store.duplicateRows(ids);
      if (!res.ok) return setNotice({ tone: 'danger', text: res.message });
      undo.current.push({ kind: 'remove', ids: res.ids, label: 'duplicar' });
    } else {
      const res = await store.deleteRows(ids);
      if (!res.ok) return setNotice({ tone: 'danger', text: res.message });
    }
    setSelected(new Set());
    setNotice({
      tone: 'ok',
      text:
        kind === 'duplicate'
          ? `${list.length} fila(s) duplicada(s) debajo de su original.`
          : `${list.length} ejercicio(s) quitado(s).`,
    });
    store.refresh();
  }

  async function moveRow(direction: 'up' | 'down', row = current, track = true) {
    if (!row) return;
    const res = await store.moveRow(row.id, direction);
    if (!res.ok) return setNotice({ tone: 'danger', text: res.message });
    if (track)
      undo.current.push({
        kind: 'move',
        rowId: row.id,
        direction: direction === 'up' ? 'down' : 'up',
        label: `mover ${row.exercise.name}`,
      });
    setFocusRow(row.id);
    store.refresh();
  }

  async function undoLast() {
    const u = undo.current.pop();
    if (!u) return setNotice({ tone: 'warn', text: 'No hay nada que deshacer.' });
    if (u.kind === 'edit') {
      const row = rows.find((x) => x.id === u.rowId);
      if (!row) return setNotice({ tone: 'warn', text: 'Esa fila ya no existe.' });
      const ok = await save(row, u.body, {});
      if (ok) setNotice({ tone: 'ok', text: `Deshecho: ${u.label}.` });
    } else if (u.kind === 'remove') {
      const res = await store.deleteRows(u.ids);
      setNotice(
        res.ok
          ? { tone: 'ok', text: `Deshecho: ${u.label}.` }
          : { tone: 'danger', text: res.message },
      );
      store.refresh();
    } else {
      const row = rows.find((x) => x.id === u.rowId);
      if (row) await moveRow(u.direction, row, false);
      setNotice({ tone: 'ok', text: `Deshecho: ${u.label}.` });
    }
  }

  function onKeyDown(e: KeyboardEvent<HTMLTableElement>) {
    if (editing || fromField(e.target)) return;
    const mod = e.ctrlKey || e.metaKey;
    const col = COLS[active.c]!.key;
    if (e.altKey && (e.key === 'ArrowUp' || e.key === 'ArrowDown') && editable) {
      e.preventDefault();
      void moveRow(e.key === 'ArrowUp' ? 'up' : 'down');
      return;
    }
    switch (e.key) {
      case 'ArrowUp':
        e.preventDefault();
        return move(-1, 0);
      case 'ArrowDown':
        e.preventDefault();
        return move(1, 0);
      case 'ArrowLeft':
        e.preventDefault();
        return move(0, -1);
      case 'ArrowRight':
        e.preventDefault();
        return move(0, 1);
      case 'Tab':
        if (e.shiftKey ? active.c > 0 : active.c < COLS.length - 1) {
          e.preventDefault();
          return move(0, e.shiftKey ? -1 : 1);
        }
        return;
      case 'Home':
        e.preventDefault();
        wantFocus.current = true;
        return setActive((a) => ({ r: mod ? 0 : a.r, c: 0 }));
      case 'End':
        e.preventDefault();
        wantFocus.current = true;
        return setActive((a) => ({ r: mod ? rows.length - 1 : a.r, c: COLS.length - 1 }));
      case 'Enter':
      case 'F2':
        e.preventDefault();
        return startEdit(r, active.c);
      case 'Escape':
        return setSelected(new Set());
      case 'Delete':
      case 'Backspace':
        if (!editable || !current || col === 'exercise' || col === 'category') return;
        e.preventDefault();
        commitText(r, active.c, '');
        return;
      case ' ':
        if (e.shiftKey && current) {
          e.preventDefault();
          return toggle(current.id);
        }
        break;
    }
    if (mod && e.key.toLowerCase() === 'z' && editable) {
      e.preventDefault();
      void undoLast();
      return;
    }
    if (mod && e.key.toLowerCase() === 'a') {
      e.preventDefault();
      setSelected(new Set(rows.map((x) => x.id)));
      return;
    }
    if (!mod && !e.altKey && e.key.length === 1 && editable && col !== 'category') {
      e.preventDefault();
      startEdit(r, active.c, e.key);
    }
  }

  function toggle(id: string) {
    setSelected((s) => {
      const n = new Set(s);
      if (n.has(id)) n.delete(id);
      else n.add(id);
      return n;
    });
  }

  /** Keys and clipboard inside fields, buttons and links (combobox, «⋯», row options) are theirs. */
  const fromField = (t: EventTarget) =>
    !!(t as HTMLElement).closest?.('input, textarea, select, button, a, summary');

  function onCopy(e: ClipboardEvent<HTMLTableElement>) {
    if (editing || fromField(e.target)) return;
    const list = selected.size ? rows.filter((x) => selected.has(x.id)) : [];
    const text = list.length
      ? toSessionTsv(
          list.map((x) => ({
            exercise: x.exercise.name,
            category: x.category,
            prescription: x.prescription,
            notes: x.notes,
          })),
        )
      : current
        ? cellText(current, COLS[active.c]!.key)
        : '';
    e.clipboardData.setData('text/plain', text);
    e.preventDefault();
    if (list.length) setNotice({ tone: 'ok', text: `${list.length} fila(s) copiada(s).` });
  }

  function onPaste(e: ClipboardEvent<HTMLTableElement>) {
    if (editing || !editable || fromField(e.target)) return;
    const text = e.clipboardData.getData('text/plain');
    if (!text) return;
    e.preventDefault();
    if (/[\t\n]/.test(text.trim())) setPasting(text);
    else if (current && COLS[active.c]!.key !== 'category') startEdit(r, active.c, text.trim());
  }

  async function copyRows() {
    const list = targets();
    if (!list.length) return;
    try {
      await navigator.clipboard.writeText(
        toSessionTsv(
          list.map((x) => ({
            exercise: x.exercise.name,
            category: x.category,
            prescription: x.prescription,
            notes: x.notes,
          })),
        ),
      );
      setNotice({
        tone: 'ok',
        text: `${list.length} fila(s) copiada(s): pégalas en otra sesión o en Excel.`,
      });
    } catch {
      setNotice({ tone: 'warn', text: 'El navegador no permite copiar: usa Ctrl+C en la tabla.' });
    }
  }

  let index = -1;
  return (
    <div className="flex flex-col gap-2">
      {editable ? (
        <div
          className="flex flex-wrap items-center gap-2"
          role="toolbar"
          aria-label="Acciones de la tabla"
        >
          <Button size="sm" variant="secondary" onClick={() => setPasting('')}>
            Pegar desde Excel
          </Button>
          <Button size="sm" variant="ghost" disabled={!current} onClick={() => void copyRows()}>
            Copiar
          </Button>
          <Button
            size="sm"
            variant="ghost"
            disabled={!current}
            onClick={() => void rowsAction('duplicate')}
          >
            Duplicar
          </Button>
          <Button
            size="sm"
            variant="ghost"
            disabled={!current}
            onClick={() => void rowsAction('delete')}
          >
            Quitar
          </Button>
          <Button
            size="sm"
            variant="ghost"
            aria-label="Subir fila"
            disabled={!current || selected.size > 1}
            onClick={() => void moveRow('up')}
          >
            ↑
          </Button>
          <Button
            size="sm"
            variant="ghost"
            aria-label="Bajar fila"
            disabled={!current || selected.size > 1}
            onClick={() => void moveRow('down')}
          >
            ↓
          </Button>
          <Button size="sm" variant="ghost" onClick={() => void undoLast()}>
            Deshacer
          </Button>
          <span className="text-xs text-muted">
            {selected.size
              ? `${selected.size} fila(s) seleccionada(s)`
              : current
                ? `Fila ${r + 1}: ${current.exercise.name}`
                : ''}
          </span>
        </div>
      ) : null}

      {pasting !== null ? (
        <PastePanel
          gridId={gridId}
          initial={pasting}
          onAdd={(rows) => store.addRows(rows)}
          onDone={(ids) => {
            setPasting(null);
            if (ids.length) {
              undo.current.push({ kind: 'remove', ids, label: `pegar ${ids.length} filas` });
              setFocusRow(ids[0]!);
              setNotice({ tone: 'ok', text: `${ids.length} ejercicio(s) añadido(s).` });
              store.refresh();
            }
          }}
        />
      ) : null}

      <div className="overflow-x-auto rounded-md border border-border">
        <table
          ref={grid}
          role="grid"
          aria-label="Ejercicios de la sesión"
          aria-describedby={`${gridId}-grid-help`}
          className="w-full border-collapse text-sm"
          onKeyDown={onKeyDown}
          onCopy={onCopy}
          onPaste={onPaste}
        >
          <thead className="bg-surface text-xs text-muted uppercase">
            <tr>
              <th scope="col" className="w-10 border-b border-border px-2 py-2">
                <span className="sr-only">Fila</span>#
              </th>
              {COLS.map((c) => (
                <th
                  key={c.key}
                  scope="col"
                  title={c.title}
                  className={`border-b border-border px-2 py-2 text-center font-semibold ${c.cls}`}
                >
                  {c.label}
                </th>
              ))}
              <th scope="col" className="w-10 border-b border-border">
                <span className="sr-only">Más opciones</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {blocks.map((b) => (
              <Fragment key={b.id}>
                {b.title && blocks.length > 1 ? (
                  <tr>
                    <td
                      colSpan={COLS.length + 2}
                      className="border-b border-border bg-surface/60 px-2 py-1 text-xs font-semibold text-muted"
                    >
                      {b.title}
                    </td>
                  </tr>
                ) : null}
                {b.rows.map((row) => {
                  index++;
                  const ri = index;
                  const isSel = selected.has(row.id);
                  return (
                    <Fragment key={row.id}>
                      <tr aria-selected={isSel} className={isSel ? 'bg-accent/10' : undefined}>
                        <td className="border-b border-border px-2 text-center text-xs text-muted">
                          <label className="flex items-center justify-center gap-1">
                            <input
                              type="checkbox"
                              checked={isSel}
                              onChange={() => toggle(row.id)}
                              aria-label={`Seleccionar fila ${ri + 1}: ${row.exercise.name}`}
                              tabIndex={-1}
                            />
                            <span aria-hidden="true">{ri + 1}</span>
                          </label>
                        </td>
                        {COLS.map((c, ci) => {
                          const isActive = ri === r && ci === active.c;
                          const isEditing = editing?.r === ri && editing.c === ci;
                          const errKey = `${row.id}:${c.key}`;
                          return (
                            <td
                              key={c.key}
                              role="gridcell"
                              ref={(el) => {
                                if (el) cells.current.set(`${ri}:${ci}`, el);
                                else cells.current.delete(`${ri}:${ci}`);
                              }}
                              tabIndex={isActive && !editing ? 0 : -1}
                              aria-readonly={c.key === 'category' || !editable || undefined}
                              aria-invalid={cellError?.key === errKey || undefined}
                              onMouseDown={(e) => {
                                // Was this cell already selected before this click?
                                clickedFocused.current = document.activeElement === e.currentTarget;
                              }}
                              onClick={() => {
                                setActive({ r: ri, c: ci });
                                // Like a spreadsheet: the first click selects (typing then
                                // replaces the value); a click on the selected cell edits it.
                                if (isActive && !editing && clickedFocused.current)
                                  startEdit(ri, ci);
                              }}
                              onDoubleClick={() => startEdit(ri, ci)}
                              className={`border-b border-border px-2 py-1.5 ${c.cls} ${c.key === 'exercise' || c.key === 'notes' || c.key === 'category' ? '' : 'text-center tabular-nums'} ${isActive ? 'outline-2 -outline-offset-2 outline-accent' : ''} ${cellError?.key === errKey ? 'bg-danger/10' : ''} ${c.key === 'category' ? 'text-xs text-muted' : ''}`}
                            >
                              {isEditing && c.key === 'exercise' ? (
                                <ExerciseCombobox
                                  label={`Cambiar el ejercicio de la fila ${ri + 1}`}
                                  initial={editing.text}
                                  autoFocus
                                  placeholder={row.exercise.name}
                                  onPick={(h) => changeExercise(row, h)}
                                  onCancel={() => {
                                    setEdit(null);
                                    wantFocus.current = true;
                                  }}
                                />
                              ) : isEditing ? (
                                <input
                                  autoFocus
                                  aria-label={`${c.label} de ${row.exercise.name}`}
                                  aria-invalid={!!editing.error || undefined}
                                  aria-describedby={
                                    editing.error ? `${gridId}-cell-error` : undefined
                                  }
                                  value={editing.text}
                                  onChange={(e) =>
                                    setEdit({ ...editing, text: e.target.value, error: undefined })
                                  }
                                  onKeyDown={(e) => {
                                    e.stopPropagation();
                                    if (e.key === 'Enter') {
                                      e.preventDefault();
                                      commit([1, 0]);
                                    } else if (e.key === 'Tab') {
                                      e.preventDefault();
                                      commit([0, e.shiftKey ? -1 : 1]);
                                    } else if (e.key === 'Escape') {
                                      e.preventDefault();
                                      editRef.current = null;
                                      setEdit(null);
                                      setCellError(null);
                                      wantFocus.current = true;
                                    }
                                  }}
                                  onFocus={(e) => {
                                    const end = e.currentTarget.value.length;
                                    e.currentTarget.setSelectionRange(end, end);
                                  }}
                                  onBlur={() => commit()}
                                  className={`h-8 w-full min-w-12 rounded border bg-bg px-1 ${c.key === 'notes' ? 'text-left' : 'text-center'} ${editing.error ? 'border-danger' : 'border-accent'}`}
                                />
                              ) : c.key === 'exercise' ? (
                                <span className="flex items-center gap-1">
                                  <span className="font-medium">{row.exercise.name}</span>
                                  {row.derived ? (
                                    <span
                                      className="text-xs text-accent"
                                      title="Valores generados por una regla de progresión: al cambiarlos quedan registrados como ajuste manual."
                                    >
                                      ↻<span className="sr-only"> progresión automática</span>
                                    </span>
                                  ) : null}
                                  {row.issues.length ? (
                                    <span
                                      className="text-xs text-warn"
                                      title={row.issues.join(' ')}
                                    >
                                      ⚠<span className="sr-only"> {row.issues.join(' ')}</span>
                                    </span>
                                  ) : null}
                                </span>
                              ) : (
                                cellText(row, c.key) || <span className="text-muted">·</span>
                              )}
                            </td>
                          );
                        })}
                        <td className="border-b border-border text-center">
                          {renderDetails ? (
                            <button
                              type="button"
                              // Reachable with Tab from the active row's last cell (roving focus).
                              tabIndex={ri === r ? 0 : -1}
                              aria-expanded={details === row.id}
                              aria-label={`Más opciones de ${row.exercise.name}`}
                              className="h-8 w-8 rounded text-muted hover:bg-surface hover:text-text"
                              onClick={() => setDetails(details === row.id ? null : row.id)}
                            >
                              ⋯
                            </button>
                          ) : null}
                        </td>
                      </tr>
                      {details === row.id && renderDetails ? (
                        <tr>
                          <td
                            colSpan={COLS.length + 2}
                            className="border-b border-border bg-surface/40 px-3"
                          >
                            {renderDetails(row.id)}
                          </td>
                        </tr>
                      ) : null}
                    </Fragment>
                  );
                })}
              </Fragment>
            ))}
            {editable ? (
              <tr>
                <td className="px-2 text-center text-muted">+</td>
                <td colSpan={COLS.length + 1} className="px-2 py-2">
                  <ExerciseCombobox
                    label="Añadir ejercicio a la sesión"
                    className="max-w-md"
                    onPick={(h) => void addExercise(h)}
                  />
                </td>
              </tr>
            ) : null}
            {!rows.length && !editable ? (
              <tr>
                <td colSpan={COLS.length + 2} className="px-2 py-6 text-center text-muted">
                  Sesión sin ejercicios.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
      <p id={`${gridId}-grid-help`} className="sr-only">
        Flechas para moverte, Intro o escribir para editar, Intro guarda y baja, Tabulador guarda y
        pasa a la derecha, Escape cancela. Control más Z deshace el último cambio.
      </p>
      <div aria-live="polite" className="min-h-5 text-sm">
        {cellError ? (
          <p id={`${gridId}-cell-error`} className="text-danger">
            {cellError.text}
          </p>
        ) : notice ? (
          <p
            className={
              notice.tone === 'danger'
                ? 'text-danger'
                : notice.tone === 'warn'
                  ? 'text-warn'
                  : 'text-ok'
            }
          >
            {notice.text}
          </p>
        ) : null}
      </div>
      <details className="text-xs text-muted">
        <summary className="cursor-pointer">Cómo se usa la tabla</summary>
        <ul className="mt-1 list-inside list-disc">
          <li>
            Un clic selecciona la celda y lo que escribas sustituye su valor; otro clic, Intro o F2
            la modifican. Intro guarda y baja, Tab guarda y pasa a la derecha, Esc cancela.
          </li>
          <li>
            Carga: «80», «82,5 kg», «75 %», «RPE 8», «banda roja» o «PC». Descanso: «90», «2:30» o
            «2 min».
          </li>
          <li>
            Pega filas copiadas de Excel o Google Sheets con Ctrl+V o con «Pegar desde Excel».
          </li>
          <li>
            Selecciona filas con su casilla (o Mayús+Espacio) para copiarlas, duplicarlas, moverlas
            (Alt+↑/↓) o quitarlas. Ctrl+Z deshace.
          </li>
          <li>
            Cada celda se guarda sola. Si otra persona cambió la misma fila, no se pisa: se avisa y
            se recarga.
          </li>
        </ul>
      </details>
    </div>
  );
}
