-- GENERATED by packages/db/scripts/generate-rls.ts from src/rls/policies.ts — do not edit by hand.
--> statement-breakpoint
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
      CREATE ROLE app_runtime NOLOGIN NOBYPASSRLS;
    END IF;
  END $$;
--> statement-breakpoint
GRANT app_runtime TO CURRENT_USER;
--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO app_runtime;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_org_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.org_id', true), '')::uuid $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_user_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_client_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.client_id', true), '')::uuid $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_trainer_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.trainer_id', true), '')::uuid $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_has_role(r text) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT r = ANY (string_to_array(coalesce(current_setting('app.roles', true), ''), ',')) $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_is_staff() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT app_has_role('ADMIN') OR app_has_role('TRAINER') $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_client_visible(cid uuid, corg uuid) RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT corg = app_org_id() AND (
      app_has_role('ADMIN')
      OR (app_has_role('TRAINER') AND EXISTS (
            SELECT 1 FROM trainer_client_assignments a
            WHERE a.client_id = cid AND a.trainer_id = app_trainer_id() AND a.ended_at IS NULL))
      OR (app_has_role('CLIENT') AND cid = app_client_id()))
  $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_can_access_client(cid uuid) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT EXISTS (SELECT 1 FROM clients c WHERE c.id = cid) $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION email_in_use(e text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM users WHERE lower(email) = lower(e)) $$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION email_in_use(text) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION email_in_use(text) TO app_runtime;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION inherit_scope() RETURNS trigger LANGUAGE plpgsql AS $$
  DECLARE
    parent_id uuid := (to_jsonb(NEW) ->> TG_ARGV[1])::uuid;
    p_org uuid;
    p_client uuid;
  BEGIN
    IF TG_ARGV[0] = 'import_jobs' THEN
      EXECUTE format('SELECT organization_id, NULL::uuid FROM %I WHERE id = $1', TG_ARGV[0]) INTO p_org, p_client USING parent_id;
    ELSE
      EXECUTE format('SELECT organization_id, client_id FROM %I WHERE id = $1', TG_ARGV[0]) INTO p_org, p_client USING parent_id;
    END IF;
    IF p_org IS NULL THEN
      RAISE EXCEPTION 'inherit_scope: parent %.% not found', TG_ARGV[0], parent_id USING ERRCODE = 'foreign_key_violation';
    END IF;
    NEW.organization_id := p_org;
    IF TG_ARGV[0] <> 'import_jobs' THEN
      NEW.client_id := p_client;
    END IF;
    RETURN NEW;
  END $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION check_client_org() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
  BEGIN
    IF NEW.client_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM clients WHERE id = NEW.client_id AND organization_id = NEW.organization_id) THEN
      RAISE EXCEPTION 'client % does not belong to organization %', NEW.client_id, NEW.organization_id USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END $$;
--> statement-breakpoint
DROP TRIGGER IF EXISTS plan_revisions_inherit_scope ON plan_revisions; CREATE TRIGGER plan_revisions_inherit_scope BEFORE INSERT OR UPDATE ON plan_revisions FOR EACH ROW EXECUTE FUNCTION inherit_scope('training_plans', 'plan_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS phases_inherit_scope ON phases; CREATE TRIGGER phases_inherit_scope BEFORE INSERT OR UPDATE ON phases FOR EACH ROW EXECUTE FUNCTION inherit_scope('training_plans', 'plan_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS mesocycles_inherit_scope ON mesocycles; CREATE TRIGGER mesocycles_inherit_scope BEFORE INSERT OR UPDATE ON mesocycles FOR EACH ROW EXECUTE FUNCTION inherit_scope('phases', 'phase_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS microcycles_inherit_scope ON microcycles; CREATE TRIGGER microcycles_inherit_scope BEFORE INSERT OR UPDATE ON microcycles FOR EACH ROW EXECUTE FUNCTION inherit_scope('mesocycles', 'mesocycle_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS sessions_inherit_scope ON sessions; CREATE TRIGGER sessions_inherit_scope BEFORE INSERT OR UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION inherit_scope('microcycles', 'microcycle_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS session_blocks_inherit_scope ON session_blocks; CREATE TRIGGER session_blocks_inherit_scope BEFORE INSERT OR UPDATE ON session_blocks FOR EACH ROW EXECUTE FUNCTION inherit_scope('sessions', 'session_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS session_exercises_inherit_scope ON session_exercises; CREATE TRIGGER session_exercises_inherit_scope BEFORE INSERT OR UPDATE ON session_exercises FOR EACH ROW EXECUTE FUNCTION inherit_scope('session_blocks', 'block_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS exercise_sets_inherit_scope ON exercise_sets; CREATE TRIGGER exercise_sets_inherit_scope BEFORE INSERT OR UPDATE ON exercise_sets FOR EACH ROW EXECUTE FUNCTION inherit_scope('session_exercises', 'session_exercise_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS attendance_inherit_scope ON attendance; CREATE TRIGGER attendance_inherit_scope BEFORE INSERT OR UPDATE ON attendance FOR EACH ROW EXECUTE FUNCTION inherit_scope('sessions', 'session_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS set_logs_inherit_scope ON set_logs; CREATE TRIGGER set_logs_inherit_scope BEFORE INSERT OR UPDATE ON set_logs FOR EACH ROW EXECUTE FUNCTION inherit_scope('sessions', 'session_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS feedback_inherit_scope ON feedback; CREATE TRIGGER feedback_inherit_scope BEFORE INSERT OR UPDATE ON feedback FOR EACH ROW EXECUTE FUNCTION inherit_scope('sessions', 'session_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS exercise_feedback_inherit_scope ON exercise_feedback; CREATE TRIGGER exercise_feedback_inherit_scope BEFORE INSERT OR UPDATE ON exercise_feedback FOR EACH ROW EXECUTE FUNCTION inherit_scope('sessions', 'session_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS assessment_results_inherit_scope ON assessment_results; CREATE TRIGGER assessment_results_inherit_scope BEFORE INSERT OR UPDATE ON assessment_results FOR EACH ROW EXECUTE FUNCTION inherit_scope('assessments', 'assessment_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS import_rows_inherit_scope ON import_rows; CREATE TRIGGER import_rows_inherit_scope BEFORE INSERT OR UPDATE ON import_rows FOR EACH ROW EXECUTE FUNCTION inherit_scope('import_jobs', 'job_id');
--> statement-breakpoint
DROP TRIGGER IF EXISTS trainer_client_assignments_check_client_org ON trainer_client_assignments; CREATE TRIGGER trainer_client_assignments_check_client_org BEFORE INSERT OR UPDATE ON trainer_client_assignments FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS training_plans_check_client_org ON training_plans; CREATE TRIGGER training_plans_check_client_org BEFORE INSERT OR UPDATE ON training_plans FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS assessments_check_client_org ON assessments; CREATE TRIGGER assessments_check_client_org BEFORE INSERT OR UPDATE ON assessments FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS derived_metrics_check_client_org ON derived_metrics; CREATE TRIGGER derived_metrics_check_client_org BEFORE INSERT OR UPDATE ON derived_metrics FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS readiness_check_client_org ON readiness; CREATE TRIGGER readiness_check_client_org BEFORE INSERT OR UPDATE ON readiness FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS pain_logs_check_client_org ON pain_logs; CREATE TRIGGER pain_logs_check_client_org BEFORE INSERT OR UPDATE ON pain_logs FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS exercise_substitutions_check_client_org ON exercise_substitutions; CREATE TRIGGER exercise_substitutions_check_client_org BEFORE INSERT OR UPDATE ON exercise_substitutions FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS exercise_tolerances_check_client_org ON exercise_tolerances; CREATE TRIGGER exercise_tolerances_check_client_org BEFORE INSERT OR UPDATE ON exercise_tolerances FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS recommendations_check_client_org ON recommendations; CREATE TRIGGER recommendations_check_client_org BEFORE INSERT OR UPDATE ON recommendations FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS alerts_check_client_org ON alerts; CREATE TRIGGER alerts_check_client_org BEFORE INSERT OR UPDATE ON alerts FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS manual_overrides_check_client_org ON manual_overrides; CREATE TRIGGER manual_overrides_check_client_org BEFORE INSERT OR UPDATE ON manual_overrides FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS client_rule_overrides_check_client_org ON client_rule_overrides; CREATE TRIGGER client_rule_overrides_check_client_org BEFORE INSERT OR UPDATE ON client_rule_overrides FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS files_check_client_org ON files; CREATE TRIGGER files_check_client_org BEFORE INSERT OR UPDATE ON files FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS reports_check_client_org ON reports; CREATE TRIGGER reports_check_client_org BEFORE INSERT OR UPDATE ON reports FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS integration_connections_check_client_org ON integration_connections; CREATE TRIGGER integration_connections_check_client_org BEFORE INSERT OR UPDATE ON integration_connections FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
DROP TRIGGER IF EXISTS external_measurements_check_client_org ON external_measurements; CREATE TRIGGER external_measurements_check_client_org BEFORE INSERT OR UPDATE ON external_measurements FOR EACH ROW EXECUTE FUNCTION check_client_org();
--> statement-breakpoint
GRANT SELECT ON roles TO app_runtime;
--> statement-breakpoint
GRANT SELECT ON permissions TO app_runtime;
--> statement-breakpoint
GRANT SELECT ON role_permissions TO app_runtime;
--> statement-breakpoint
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'login_attempts' LOOP
    EXECUTE format('DROP POLICY %I ON login_attempts', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'password_reset_tokens' LOOP
    EXECUTE format('DROP POLICY %I ON password_reset_tokens', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'organizations' LOOP
    EXECUTE format('DROP POLICY %I ON organizations', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON organizations TO app_runtime;
--> statement-breakpoint
CREATE POLICY organizations_select ON organizations FOR SELECT USING (id = app_org_id());
--> statement-breakpoint
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'users' LOOP
    EXECUTE format('DROP POLICY %I ON users', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO app_runtime;
--> statement-breakpoint
CREATE POLICY users_select ON users FOR SELECT USING (organization_id = app_org_id() AND (app_is_staff() OR id = app_user_id()));
CREATE POLICY users_update ON users FOR UPDATE USING (organization_id = app_org_id() AND (app_has_role('ADMIN') OR id = app_user_id())) WITH CHECK (organization_id = app_org_id());
--> statement-breakpoint
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'user_roles' LOOP
    EXECUTE format('DROP POLICY %I ON user_roles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON user_roles TO app_runtime;
--> statement-breakpoint
CREATE POLICY user_roles_select ON user_roles FOR SELECT USING (organization_id = app_org_id() AND (app_is_staff() OR user_id = app_user_id()));
CREATE POLICY user_roles_write ON user_roles FOR ALL USING (organization_id = app_org_id() AND app_has_role('ADMIN')) WITH CHECK (organization_id = app_org_id() AND app_has_role('ADMIN'));
--> statement-breakpoint
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'auth_sessions' LOOP
    EXECUTE format('DROP POLICY %I ON auth_sessions', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON auth_sessions TO app_runtime;
--> statement-breakpoint
CREATE POLICY auth_sessions_all ON auth_sessions FOR ALL
  USING (user_id = app_user_id() OR (app_has_role('ADMIN') AND EXISTS (SELECT 1 FROM users u WHERE u.id = auth_sessions.user_id)))
  WITH CHECK (user_id = app_user_id() OR (app_has_role('ADMIN') AND EXISTS (SELECT 1 FROM users u WHERE u.id = auth_sessions.user_id)));
--> statement-breakpoint
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'invitations' LOOP
    EXECUTE format('DROP POLICY %I ON invitations', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON invitations TO app_runtime;
--> statement-breakpoint
CREATE POLICY invitations_all ON invitations FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE trainers ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'trainers' LOOP
    EXECUTE format('DROP POLICY %I ON trainers', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON trainers TO app_runtime;
--> statement-breakpoint
CREATE POLICY trainers_select ON trainers FOR SELECT USING (organization_id = app_org_id());
CREATE POLICY trainers_write ON trainers FOR ALL USING (organization_id = app_org_id() AND app_has_role('ADMIN')) WITH CHECK (organization_id = app_org_id() AND app_has_role('ADMIN'));
--> statement-breakpoint
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'audit_logs' LOOP
    EXECUTE format('DROP POLICY %I ON audit_logs', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON audit_logs TO app_runtime;
--> statement-breakpoint
CREATE POLICY audit_logs_select ON audit_logs FOR SELECT USING (organization_id = app_org_id() AND app_is_staff() AND (client_id IS NULL OR app_can_access_client(client_id)));
CREATE POLICY audit_logs_insert ON audit_logs FOR INSERT WITH CHECK (organization_id = app_org_id() AND actor_user_id = app_user_id());
--> statement-breakpoint
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'clients' LOOP
    EXECUTE format('DROP POLICY %I ON clients', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON clients TO app_runtime;
--> statement-breakpoint
CREATE POLICY clients_select ON clients FOR SELECT USING (app_client_visible(id, organization_id));
CREATE POLICY clients_insert ON clients FOR INSERT WITH CHECK (organization_id = app_org_id() AND app_is_staff());
CREATE POLICY clients_update ON clients FOR UPDATE USING (app_client_visible(id, organization_id)) WITH CHECK (organization_id = app_org_id());
CREATE POLICY clients_delete ON clients FOR DELETE USING (organization_id = app_org_id() AND app_has_role('ADMIN'));
--> statement-breakpoint
ALTER TABLE trainer_client_assignments ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'trainer_client_assignments' LOOP
    EXECUTE format('DROP POLICY %I ON trainer_client_assignments', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON trainer_client_assignments TO app_runtime;
--> statement-breakpoint
CREATE POLICY tca_select ON trainer_client_assignments FOR SELECT USING (organization_id = app_org_id() AND (app_is_staff() OR client_id = app_client_id()));
CREATE POLICY tca_write ON trainer_client_assignments FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE client_training_profiles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'client_training_profiles' LOOP
    EXECUTE format('DROP POLICY %I ON client_training_profiles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON client_training_profiles TO app_runtime;
--> statement-breakpoint
CREATE POLICY client_training_profiles_select ON client_training_profiles FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY client_training_profiles_write ON client_training_profiles FOR ALL USING (app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE client_availability ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'client_availability' LOOP
    EXECUTE format('DROP POLICY %I ON client_availability', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON client_availability TO app_runtime;
--> statement-breakpoint
CREATE POLICY client_availability_select ON client_availability FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY client_availability_write ON client_availability FOR ALL USING (app_can_access_client(client_id)) WITH CHECK (app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE client_equipment ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'client_equipment' LOOP
    EXECUTE format('DROP POLICY %I ON client_equipment', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON client_equipment TO app_runtime;
--> statement-breakpoint
CREATE POLICY client_equipment_select ON client_equipment FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY client_equipment_write ON client_equipment FOR ALL USING (app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE client_goals ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'client_goals' LOOP
    EXECUTE format('DROP POLICY %I ON client_goals', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON client_goals TO app_runtime;
--> statement-breakpoint
CREATE POLICY client_goals_select ON client_goals FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY client_goals_write ON client_goals FOR ALL USING (app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE client_history_entries ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'client_history_entries' LOOP
    EXECUTE format('DROP POLICY %I ON client_history_entries', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON client_history_entries TO app_runtime;
--> statement-breakpoint
CREATE POLICY client_history_entries_select ON client_history_entries FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY client_history_entries_write ON client_history_entries FOR ALL USING (app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE health_declarations ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'health_declarations' LOOP
    EXECUTE format('DROP POLICY %I ON health_declarations', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON health_declarations TO app_runtime;
--> statement-breakpoint
CREATE POLICY health_declarations_select ON health_declarations FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY health_declarations_write ON health_declarations FOR ALL USING (app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE screening_responses ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'screening_responses' LOOP
    EXECUTE format('DROP POLICY %I ON screening_responses', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON screening_responses TO app_runtime;
--> statement-breakpoint
CREATE POLICY screening_responses_select ON screening_responses FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY screening_responses_write ON screening_responses FOR ALL USING (app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE consents ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'consents' LOOP
    EXECUTE format('DROP POLICY %I ON consents', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON consents TO app_runtime;
--> statement-breakpoint
CREATE POLICY consents_select ON consents FOR SELECT USING (app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY consents_write ON consents FOR ALL USING (app_can_access_client(client_id)) WITH CHECK (app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'goals' LOOP
    EXECUTE format('DROP POLICY %I ON goals', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON goals TO app_runtime;
--> statement-breakpoint
CREATE POLICY goals_select ON goals FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY goals_write ON goals FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE sports ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'sports' LOOP
    EXECUTE format('DROP POLICY %I ON sports', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON sports TO app_runtime;
--> statement-breakpoint
CREATE POLICY sports_select ON sports FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY sports_write ON sports FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'equipment' LOOP
    EXECUTE format('DROP POLICY %I ON equipment', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON equipment TO app_runtime;
--> statement-breakpoint
CREATE POLICY equipment_select ON equipment FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY equipment_write ON equipment FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE movement_patterns ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'movement_patterns' LOOP
    EXECUTE format('DROP POLICY %I ON movement_patterns', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON movement_patterns TO app_runtime;
--> statement-breakpoint
CREATE POLICY movement_patterns_select ON movement_patterns FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY movement_patterns_write ON movement_patterns FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE muscles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'muscles' LOOP
    EXECUTE format('DROP POLICY %I ON muscles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON muscles TO app_runtime;
--> statement-breakpoint
CREATE POLICY muscles_select ON muscles FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY muscles_write ON muscles FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_categories ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_categories' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_categories', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_categories TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_categories_select ON exercise_categories FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY exercise_categories_write ON exercise_categories FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_tags ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_tags' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_tags', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_tags TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_tags_select ON exercise_tags FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY exercise_tags_write ON exercise_tags FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE prescription_variables ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'prescription_variables' LOOP
    EXECUTE format('DROP POLICY %I ON prescription_variables', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON prescription_variables TO app_runtime;
--> statement-breakpoint
CREATE POLICY prescription_variables_select ON prescription_variables FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY prescription_variables_write ON prescription_variables FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE prescription_profiles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'prescription_profiles' LOOP
    EXECUTE format('DROP POLICY %I ON prescription_profiles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON prescription_profiles TO app_runtime;
--> statement-breakpoint
CREATE POLICY prescription_profiles_select ON prescription_profiles FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY prescription_profiles_write ON prescription_profiles FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercises' LOOP
    EXECUTE format('DROP POLICY %I ON exercises', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercises TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercises_select ON exercises FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY exercises_write ON exercises FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_progressions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_progressions' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_progressions', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_progressions TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_progressions_select ON exercise_progressions FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY exercise_progressions_write ON exercise_progressions FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_category_links ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_category_links' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_category_links', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_category_links TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_category_links_select ON exercise_category_links FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_category_links.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_category_links_write ON exercise_category_links FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_category_links.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_category_links.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_tag_links ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_tag_links' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_tag_links', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_tag_links TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_tag_links_select ON exercise_tag_links FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_tag_links.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_tag_links_write ON exercise_tag_links FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_tag_links.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_tag_links.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_muscles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_muscles' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_muscles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_muscles TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_muscles_select ON exercise_muscles FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_muscles.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_muscles_write ON exercise_muscles FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_muscles.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_muscles.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_equipment ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_equipment' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_equipment', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_equipment TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_equipment_select ON exercise_equipment FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_equipment.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_equipment_write ON exercise_equipment FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_equipment.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_equipment.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_media ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_media' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_media', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_media TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_media_select ON exercise_media FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_media.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_media_write ON exercise_media FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_media.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_media.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_instructions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_instructions' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_instructions', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_instructions TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_instructions_select ON exercise_instructions FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_instructions.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_instructions_write ON exercise_instructions FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_instructions.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_instructions.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_method_links ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_method_links' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_method_links', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_method_links TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_method_links_select ON exercise_method_links FOR SELECT USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_method_links.exercise_id));
--> statement-breakpoint
CREATE POLICY exercise_method_links_write ON exercise_method_links FOR ALL USING (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_method_links.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM exercises x WHERE x.id = exercise_method_links.exercise_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE populations ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'populations' LOOP
    EXECUTE format('DROP POLICY %I ON populations', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON populations TO app_runtime;
--> statement-breakpoint
CREATE POLICY populations_select ON populations FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY populations_write ON populations FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE outcomes ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'outcomes' LOOP
    EXECUTE format('DROP POLICY %I ON outcomes', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON outcomes TO app_runtime;
--> statement-breakpoint
CREATE POLICY outcomes_select ON outcomes FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY outcomes_write ON outcomes FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE evidence_sources ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'evidence_sources' LOOP
    EXECUTE format('DROP POLICY %I ON evidence_sources', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON evidence_sources TO app_runtime;
--> statement-breakpoint
CREATE POLICY evidence_sources_select ON evidence_sources FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY evidence_sources_write ON evidence_sources FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE evidence_findings ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'evidence_findings' LOOP
    EXECUTE format('DROP POLICY %I ON evidence_findings', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON evidence_findings TO app_runtime;
--> statement-breakpoint
CREATE POLICY evidence_findings_select ON evidence_findings FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY evidence_findings_write ON evidence_findings FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE knowledge_claims ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'knowledge_claims' LOOP
    EXECUTE format('DROP POLICY %I ON knowledge_claims', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON knowledge_claims TO app_runtime;
--> statement-breakpoint
CREATE POLICY knowledge_claims_select ON knowledge_claims FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY knowledge_claims_write ON knowledge_claims FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE claim_evidence ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'claim_evidence' LOOP
    EXECUTE format('DROP POLICY %I ON claim_evidence', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON claim_evidence TO app_runtime;
--> statement-breakpoint
CREATE POLICY claim_evidence_select ON claim_evidence FOR SELECT USING (EXISTS (SELECT 1 FROM knowledge_claims x WHERE x.id = claim_evidence.claim_id));
--> statement-breakpoint
CREATE POLICY claim_evidence_write ON claim_evidence FOR ALL USING (EXISTS (SELECT 1 FROM knowledge_claims x WHERE x.id = claim_evidence.claim_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM knowledge_claims x WHERE x.id = claim_evidence.claim_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE methods ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'methods' LOOP
    EXECUTE format('DROP POLICY %I ON methods', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON methods TO app_runtime;
--> statement-breakpoint
CREATE POLICY methods_select ON methods FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY methods_write ON methods FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE method_variables ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'method_variables' LOOP
    EXECUTE format('DROP POLICY %I ON method_variables', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON method_variables TO app_runtime;
--> statement-breakpoint
CREATE POLICY method_variables_select ON method_variables FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY method_variables_write ON method_variables FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE method_evidence ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'method_evidence' LOOP
    EXECUTE format('DROP POLICY %I ON method_evidence', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON method_evidence TO app_runtime;
--> statement-breakpoint
CREATE POLICY method_evidence_select ON method_evidence FOR SELECT USING (EXISTS (SELECT 1 FROM methods x WHERE x.id = method_evidence.method_id));
--> statement-breakpoint
CREATE POLICY method_evidence_write ON method_evidence FOR ALL USING (EXISTS (SELECT 1 FROM methods x WHERE x.id = method_evidence.method_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM methods x WHERE x.id = method_evidence.method_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE method_notes ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'method_notes' LOOP
    EXECUTE format('DROP POLICY %I ON method_notes', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON method_notes TO app_runtime;
--> statement-breakpoint
CREATE POLICY method_notes_select ON method_notes FOR SELECT USING (EXISTS (SELECT 1 FROM methods x WHERE x.id = method_notes.method_id));
--> statement-breakpoint
CREATE POLICY method_notes_write ON method_notes FOR ALL USING (EXISTS (SELECT 1 FROM methods x WHERE x.id = method_notes.method_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM methods x WHERE x.id = method_notes.method_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE evidence_reviews ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'evidence_reviews' LOOP
    EXECUTE format('DROP POLICY %I ON evidence_reviews', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON evidence_reviews TO app_runtime;
--> statement-breakpoint
CREATE POLICY evidence_reviews_select ON evidence_reviews FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY evidence_reviews_write ON evidence_reviews FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE assessment_tests ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'assessment_tests' LOOP
    EXECUTE format('DROP POLICY %I ON assessment_tests', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON assessment_tests TO app_runtime;
--> statement-breakpoint
CREATE POLICY assessment_tests_select ON assessment_tests FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY assessment_tests_write ON assessment_tests FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE test_reliability_data ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'test_reliability_data' LOOP
    EXECUTE format('DROP POLICY %I ON test_reliability_data', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON test_reliability_data TO app_runtime;
--> statement-breakpoint
CREATE POLICY test_reliability_data_select ON test_reliability_data FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY test_reliability_data_write ON test_reliability_data FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE reference_values ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reference_values' LOOP
    EXECUTE format('DROP POLICY %I ON reference_values', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON reference_values TO app_runtime;
--> statement-breakpoint
CREATE POLICY reference_values_select ON reference_values FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY reference_values_write ON reference_values FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE assessment_batteries ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'assessment_batteries' LOOP
    EXECUTE format('DROP POLICY %I ON assessment_batteries', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON assessment_batteries TO app_runtime;
--> statement-breakpoint
CREATE POLICY assessment_batteries_select ON assessment_batteries FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY assessment_batteries_write ON assessment_batteries FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE battery_tests ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'battery_tests' LOOP
    EXECUTE format('DROP POLICY %I ON battery_tests', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON battery_tests TO app_runtime;
--> statement-breakpoint
CREATE POLICY battery_tests_select ON battery_tests FOR SELECT USING (EXISTS (SELECT 1 FROM assessment_batteries x WHERE x.id = battery_tests.battery_id));
--> statement-breakpoint
CREATE POLICY battery_tests_write ON battery_tests FOR ALL USING (EXISTS (SELECT 1 FROM assessment_batteries x WHERE x.id = battery_tests.battery_id AND x.organization_id = app_org_id()) AND app_is_staff()) WITH CHECK (EXISTS (SELECT 1 FROM assessment_batteries x WHERE x.id = battery_tests.battery_id AND x.organization_id = app_org_id()) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE rule_sets ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'rule_sets' LOOP
    EXECUTE format('DROP POLICY %I ON rule_sets', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON rule_sets TO app_runtime;
--> statement-breakpoint
CREATE POLICY rule_sets_select ON rule_sets FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY rule_sets_write ON rule_sets FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE rules ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'rules' LOOP
    EXECUTE format('DROP POLICY %I ON rules', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON rules TO app_runtime;
--> statement-breakpoint
CREATE POLICY rules_select ON rules FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY rules_write ON rules FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'assessments' LOOP
    EXECUTE format('DROP POLICY %I ON assessments', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON assessments TO app_runtime;
--> statement-breakpoint
CREATE POLICY assessments_select ON assessments FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY assessments_write ON assessments FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'assessment_results' LOOP
    EXECUTE format('DROP POLICY %I ON assessment_results', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON assessment_results TO app_runtime;
--> statement-breakpoint
CREATE POLICY assessment_results_select ON assessment_results FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY assessment_results_write ON assessment_results FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE derived_metrics ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'derived_metrics' LOOP
    EXECUTE format('DROP POLICY %I ON derived_metrics', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON derived_metrics TO app_runtime;
--> statement-breakpoint
CREATE POLICY derived_metrics_select ON derived_metrics FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY derived_metrics_write ON derived_metrics FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE plan_templates ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'plan_templates' LOOP
    EXECUTE format('DROP POLICY %I ON plan_templates', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON plan_templates TO app_runtime;
--> statement-breakpoint
CREATE POLICY plan_templates_select ON plan_templates FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());
--> statement-breakpoint
CREATE POLICY plan_templates_write ON plan_templates FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE training_plans ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'training_plans' LOOP
    EXECUTE format('DROP POLICY %I ON training_plans', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON training_plans TO app_runtime;
--> statement-breakpoint
CREATE POLICY training_plans_select ON training_plans FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY training_plans_write ON training_plans FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE plan_revisions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'plan_revisions' LOOP
    EXECUTE format('DROP POLICY %I ON plan_revisions', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON plan_revisions TO app_runtime;
--> statement-breakpoint
CREATE POLICY plan_revisions_select ON plan_revisions FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY plan_revisions_write ON plan_revisions FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE phases ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'phases' LOOP
    EXECUTE format('DROP POLICY %I ON phases', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON phases TO app_runtime;
--> statement-breakpoint
CREATE POLICY phases_select ON phases FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY phases_write ON phases FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE mesocycles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'mesocycles' LOOP
    EXECUTE format('DROP POLICY %I ON mesocycles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON mesocycles TO app_runtime;
--> statement-breakpoint
CREATE POLICY mesocycles_select ON mesocycles FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY mesocycles_write ON mesocycles FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE microcycles ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'microcycles' LOOP
    EXECUTE format('DROP POLICY %I ON microcycles', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON microcycles TO app_runtime;
--> statement-breakpoint
CREATE POLICY microcycles_select ON microcycles FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY microcycles_write ON microcycles FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'sessions' LOOP
    EXECUTE format('DROP POLICY %I ON sessions', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON sessions TO app_runtime;
--> statement-breakpoint
CREATE POLICY sessions_select ON sessions FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY sessions_write ON sessions FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE session_blocks ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'session_blocks' LOOP
    EXECUTE format('DROP POLICY %I ON session_blocks', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON session_blocks TO app_runtime;
--> statement-breakpoint
CREATE POLICY session_blocks_select ON session_blocks FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY session_blocks_write ON session_blocks FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE session_exercises ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'session_exercises' LOOP
    EXECUTE format('DROP POLICY %I ON session_exercises', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON session_exercises TO app_runtime;
--> statement-breakpoint
CREATE POLICY session_exercises_select ON session_exercises FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY session_exercises_write ON session_exercises FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE exercise_sets ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_sets' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_sets', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_sets TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_sets_select ON exercise_sets FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY exercise_sets_write ON exercise_sets FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'attendance' LOOP
    EXECUTE format('DROP POLICY %I ON attendance', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON attendance TO app_runtime;
--> statement-breakpoint
CREATE POLICY attendance_select ON attendance FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY attendance_write ON attendance FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE set_logs ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'set_logs' LOOP
    EXECUTE format('DROP POLICY %I ON set_logs', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON set_logs TO app_runtime;
--> statement-breakpoint
CREATE POLICY set_logs_select ON set_logs FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY set_logs_write ON set_logs FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'feedback' LOOP
    EXECUTE format('DROP POLICY %I ON feedback', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON feedback TO app_runtime;
--> statement-breakpoint
CREATE POLICY feedback_select ON feedback FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY feedback_write ON feedback FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE exercise_feedback ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_feedback' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_feedback', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_feedback TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_feedback_select ON exercise_feedback FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY exercise_feedback_write ON exercise_feedback FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE readiness ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'readiness' LOOP
    EXECUTE format('DROP POLICY %I ON readiness', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON readiness TO app_runtime;
--> statement-breakpoint
CREATE POLICY readiness_select ON readiness FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY readiness_write ON readiness FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE pain_logs ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pain_logs' LOOP
    EXECUTE format('DROP POLICY %I ON pain_logs', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON pain_logs TO app_runtime;
--> statement-breakpoint
CREATE POLICY pain_logs_select ON pain_logs FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY pain_logs_write ON pain_logs FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE exercise_substitutions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_substitutions' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_substitutions', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_substitutions TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_substitutions_select ON exercise_substitutions FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY exercise_substitutions_write ON exercise_substitutions FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id)) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
ALTER TABLE exercise_tolerances ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'exercise_tolerances' LOOP
    EXECUTE format('DROP POLICY %I ON exercise_tolerances', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON exercise_tolerances TO app_runtime;
--> statement-breakpoint
CREATE POLICY exercise_tolerances_select ON exercise_tolerances FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY exercise_tolerances_write ON exercise_tolerances FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'recommendations' LOOP
    EXECUTE format('DROP POLICY %I ON recommendations', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON recommendations TO app_runtime;
--> statement-breakpoint
CREATE POLICY recommendations_select ON recommendations FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY recommendations_write ON recommendations FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE recommendation_evidence ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'recommendation_evidence' LOOP
    EXECUTE format('DROP POLICY %I ON recommendation_evidence', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON recommendation_evidence TO app_runtime;
--> statement-breakpoint
CREATE POLICY recommendation_evidence_all ON recommendation_evidence FOR ALL
  USING (EXISTS (SELECT 1 FROM recommendations r WHERE r.id = recommendation_evidence.recommendation_id))
  WITH CHECK (EXISTS (SELECT 1 FROM recommendations r WHERE r.id = recommendation_evidence.recommendation_id));
--> statement-breakpoint
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'alerts' LOOP
    EXECUTE format('DROP POLICY %I ON alerts', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON alerts TO app_runtime;
--> statement-breakpoint
CREATE POLICY alerts_select ON alerts FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY alerts_write ON alerts FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE manual_overrides ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'manual_overrides' LOOP
    EXECUTE format('DROP POLICY %I ON manual_overrides', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON manual_overrides TO app_runtime;
--> statement-breakpoint
CREATE POLICY manual_overrides_select ON manual_overrides FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY manual_overrides_write ON manual_overrides FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE client_rule_overrides ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'client_rule_overrides' LOOP
    EXECUTE format('DROP POLICY %I ON client_rule_overrides', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON client_rule_overrides TO app_runtime;
--> statement-breakpoint
CREATE POLICY client_rule_overrides_select ON client_rule_overrides FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY client_rule_overrides_write ON client_rule_overrides FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'notifications' LOOP
    EXECUTE format('DROP POLICY %I ON notifications', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON notifications TO app_runtime;
--> statement-breakpoint
CREATE POLICY notifications_select ON notifications FOR SELECT USING (organization_id = app_org_id() AND user_id = app_user_id());
CREATE POLICY notifications_update ON notifications FOR UPDATE USING (organization_id = app_org_id() AND user_id = app_user_id()) WITH CHECK (organization_id = app_org_id() AND user_id = app_user_id());
CREATE POLICY notifications_insert ON notifications FOR INSERT WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'files' LOOP
    EXECUTE format('DROP POLICY %I ON files', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON files TO app_runtime;
--> statement-breakpoint
CREATE POLICY files_select ON files FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
CREATE POLICY files_write ON files FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END)) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END));
--> statement-breakpoint
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reports' LOOP
    EXECUTE format('DROP POLICY %I ON reports', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON reports TO app_runtime;
--> statement-breakpoint
CREATE POLICY reports_select ON reports FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY reports_write ON reports FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE import_jobs ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'import_jobs' LOOP
    EXECUTE format('DROP POLICY %I ON import_jobs', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON import_jobs TO app_runtime;
--> statement-breakpoint
CREATE POLICY import_jobs_all ON import_jobs FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE import_rows ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'import_rows' LOOP
    EXECUTE format('DROP POLICY %I ON import_rows', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON import_rows TO app_runtime;
--> statement-breakpoint
CREATE POLICY import_rows_all ON import_rows FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());
--> statement-breakpoint
ALTER TABLE domain_events ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'domain_events' LOOP
    EXECUTE format('DROP POLICY %I ON domain_events', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON domain_events TO app_runtime;
--> statement-breakpoint
CREATE POLICY domain_events_insert ON domain_events FOR INSERT WITH CHECK (organization_id = app_org_id());
--> statement-breakpoint
ALTER TABLE integration_connections ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'integration_connections' LOOP
    EXECUTE format('DROP POLICY %I ON integration_connections', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON integration_connections TO app_runtime;
--> statement-breakpoint
CREATE POLICY integration_connections_select ON integration_connections FOR SELECT USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
CREATE POLICY integration_connections_write ON integration_connections FOR ALL USING (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND (CASE WHEN client_id IS NULL THEN app_is_staff() ELSE app_can_access_client(client_id) END) AND app_is_staff());
--> statement-breakpoint
ALTER TABLE external_measurements ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'external_measurements' LOOP
    EXECUTE format('DROP POLICY %I ON external_measurements', p.policyname);
  END LOOP;
END $$;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON external_measurements TO app_runtime;
--> statement-breakpoint
CREATE POLICY external_measurements_select ON external_measurements FOR SELECT USING (organization_id = app_org_id() AND app_can_access_client(client_id));
--> statement-breakpoint
CREATE POLICY external_measurements_write ON external_measurements FOR ALL USING (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_can_access_client(client_id) AND app_is_staff());
--> statement-breakpoint
REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM app_runtime;
--> statement-breakpoint
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_runtime;
