import { createHash, createHmac } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

/** Storage port for binary files (silhouettes, images, reports): local disk or S3-compatible. */
export interface FileStorage {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  /** Erasure (RGPD art. 17): removing a missing key is not an error. */
  delete(key: string): Promise<void>;
}

export class MemoryStorage implements FileStorage {
  private readonly files = new Map<string, Uint8Array>();
  async put(key: string, bytes: Uint8Array): Promise<void> {
    this.files.set(key, bytes);
  }
  async get(key: string): Promise<Uint8Array | null> {
    return this.files.get(key) ?? null;
  }
  async delete(key: string): Promise<void> {
    this.files.delete(key);
  }
}

/** Keys are generated by the app; anything else (e.g. `../`) is refused. */
function assertKey(key: string): void {
  if (!/^[a-z0-9/_-]+\.(png|jpg|webp)$/.test(key) || key.includes('..'))
    throw new Error('invalid storage key');
}

/** Local disk adapter for single-server deployments and development. */
export class LocalDiskStorage implements FileStorage {
  constructor(private readonly root: string) {}
  private resolve(key: string): string {
    assertKey(key);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep))
      throw new Error('invalid storage key');
    return full;
  }
  async put(key: string, bytes: Uint8Array): Promise<void> {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, bytes, { flag: 'wx' });
  }
  async get(key: string): Promise<Uint8Array | null> {
    try {
      return await readFile(this.resolve(key));
    } catch {
      return null;
    }
  }
  async delete(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }
}

export interface S3Config {
  /** e.g. https://s3.fr-par.scw.cloud, https://s3.eu-west-3.amazonaws.com, http://minio:9000 */
  endpoint: string;
  region: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  /** Server-side encryption header (e.g. AES256) when the provider supports it. */
  serverSideEncryption?: string;
}

const sha256 = (data: string | Uint8Array) => createHash('sha256').update(data).digest('hex');
const hmac = (key: string | Buffer, data: string) =>
  createHmac('sha256', key).update(data).digest();
const encodeSegment = (s: string) =>
  encodeURIComponent(s).replace(
    /[!'()*]/g,
    (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`,
  );

/**
 * S3-compatible object storage (Phase 15 pending, OPERATIONS.md): AWS Signature V4 over fetch, no
 * SDK. Path-style URLs (`endpoint/bucket/key`), supported by AWS and EU providers alike. Use a bucket
 * in the EU, private, with versioning off or a short lifecycle so erasures really remove the data.
 */
export class S3Storage implements FileStorage {
  constructor(
    private readonly c: S3Config,
    private readonly now: () => Date = () => new Date(),
  ) {}

  private async send(
    method: 'PUT' | 'GET' | 'DELETE',
    key: string,
    body?: Uint8Array,
    contentType?: string,
  ) {
    assertKey(key);
    const url = new URL(this.c.endpoint);
    const path = `/${encodeSegment(this.c.bucket)}/${key.split('/').map(encodeSegment).join('/')}`;
    const amzDate = this.now()
      .toISOString()
      .replace(/[-:]/g, '')
      .replace(/\.\d{3}/, '');
    const day = amzDate.slice(0, 8);
    const payloadHash = sha256(body ?? '');
    const headers: Record<string, string> = {
      host: url.host,
      'x-amz-content-sha256': payloadHash,
      'x-amz-date': amzDate,
    };
    if (method === 'PUT') {
      headers['content-type'] = contentType ?? 'application/octet-stream';
      if (this.c.serverSideEncryption)
        headers['x-amz-server-side-encryption'] = this.c.serverSideEncryption;
    }
    const names = Object.keys(headers).sort();
    const canonical = [
      method,
      path,
      '',
      ...names.map((n) => `${n}:${headers[n]!.trim()}`),
      '',
      names.join(';'),
      payloadHash,
    ].join('\n');
    const scope = `${day}/${this.c.region}/s3/aws4_request`;
    const toSign = ['AWS4-HMAC-SHA256', amzDate, scope, sha256(canonical)].join('\n');
    const kDate = hmac(`AWS4${this.c.secretAccessKey}`, day);
    const kSigning = hmac(hmac(hmac(kDate, this.c.region), 's3'), 'aws4_request');
    const signature = createHmac('sha256', kSigning).update(toSign).digest('hex');
    const { host: _host, ...sent } = headers;
    return fetch(`${url.origin}${path}`, {
      method,
      headers: {
        ...sent,
        authorization: `AWS4-HMAC-SHA256 Credential=${this.c.accessKeyId}/${scope}, SignedHeaders=${names.join(';')}, Signature=${signature}`,
      },
      body: body ? Buffer.from(body) : undefined,
      signal: AbortSignal.timeout(15_000),
    });
  }

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    const r = await this.send('PUT', key, bytes, contentType);
    if (!r.ok) throw new Error(`object storage PUT failed (${r.status})`);
  }
  async get(key: string): Promise<Uint8Array | null> {
    const r = await this.send('GET', key);
    if (r.status === 404) return null;
    if (!r.ok) throw new Error(`object storage GET failed (${r.status})`);
    return new Uint8Array(await r.arrayBuffer());
  }
  async delete(key: string): Promise<void> {
    const r = await this.send('DELETE', key);
    if (!r.ok && r.status !== 404) throw new Error(`object storage DELETE failed (${r.status})`);
  }
}

/** Adapter from the environment: S3 when S3_BUCKET is set, local disk otherwise. */
export function storageFromEnv(
  env: Record<string, string | undefined>,
  localRoot: string,
): FileStorage {
  if (!env.S3_BUCKET) return new LocalDiskStorage(env.FILE_STORAGE_DIR || localRoot);
  const need = (k: string) => {
    const v = env[k];
    if (!v) throw new Error(`${k} is required when S3_BUCKET is set`);
    return v;
  };
  return new S3Storage({
    endpoint: need('S3_ENDPOINT'),
    region: env.S3_REGION || 'eu-west-1',
    bucket: env.S3_BUCKET,
    accessKeyId: need('S3_ACCESS_KEY_ID'),
    secretAccessKey: need('S3_SECRET_ACCESS_KEY'),
    serverSideEncryption: env.S3_SSE || undefined,
  });
}

export const IMAGE_MAX_BYTES = 2 * 1024 * 1024;

/**
 * Detects the real image type from magic bytes (the declared Content-Type is not trusted).
 * SVG is deliberately not accepted: it can carry scripts.
 */
export function sniffImage(
  bytes: Uint8Array,
): { contentType: string; ext: 'png' | 'jpg' | 'webp' } | null {
  const b = bytes;
  if (b.length > 8 && b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47)
    return { contentType: 'image/png', ext: 'png' };
  if (b.length > 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff)
    return { contentType: 'image/jpeg', ext: 'jpg' };
  if (
    b.length > 12 &&
    String.fromCharCode(b[0]!, b[1]!, b[2]!, b[3]!) === 'RIFF' &&
    String.fromCharCode(b[8]!, b[9]!, b[10]!, b[11]!) === 'WEBP'
  ) {
    return { contentType: 'image/webp', ext: 'webp' };
  }
  return null;
}
