import { CHECK_CLIENT_ORG, INHERIT_SCOPE, RLS_POLICIES } from './policies';

/**
 * Builds the full, idempotent RLS migration from the declarative map in policies.ts.
 * Re-running it on a database that already has policies drops and recreates them, so a
 * change to the map is shipped as a new migration containing the whole output.
 */
export function generateRlsSql(): string {
  const out: string[] = [];
  const stmt = (s: string) => out.push(s.trim());

  stmt(
    `-- GENERATED by packages/db/scripts/generate-rls.ts from src/rls/policies.ts — do not edit by hand.`,
  );
  stmt(`DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
      CREATE ROLE app_runtime NOLOGIN NOBYPASSRLS;
    END IF;
  END $$;`);
  stmt(`GRANT app_runtime TO CURRENT_USER;`);
  stmt(`GRANT USAGE ON SCHEMA public TO app_runtime;`);

  // Session helpers. Unset settings → NULL → every comparison fails → deny by default.
  stmt(
    `CREATE OR REPLACE FUNCTION app_org_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.org_id', true), '')::uuid $$;`,
  );
  stmt(
    `CREATE OR REPLACE FUNCTION app_user_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;`,
  );
  stmt(
    `CREATE OR REPLACE FUNCTION app_client_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.client_id', true), '')::uuid $$;`,
  );
  stmt(
    `CREATE OR REPLACE FUNCTION app_trainer_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.trainer_id', true), '')::uuid $$;`,
  );
  stmt(
    `CREATE OR REPLACE FUNCTION app_has_role(r text) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT r = ANY (string_to_array(coalesce(current_setting('app.roles', true), ''), ',')) $$;`,
  );
  stmt(
    `CREATE OR REPLACE FUNCTION app_is_staff() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT app_has_role('ADMIN') OR app_has_role('TRAINER') $$;`,
  );
  // Visibility of a client row given its id and organization (used by the clients policy itself).
  stmt(`CREATE OR REPLACE FUNCTION app_client_visible(cid uuid, corg uuid) RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT corg = app_org_id() AND (
      app_has_role('ADMIN')
      OR (app_has_role('TRAINER') AND EXISTS (
            SELECT 1 FROM trainer_client_assignments a
            WHERE a.client_id = cid AND a.trainer_id = app_trainer_id() AND a.ended_at IS NULL))
      OR (app_has_role('CLIENT') AND cid = app_client_id()))
  $$;`);
  // For child tables: is the referenced client visible (goes through clients' RLS).
  stmt(
    `CREATE OR REPLACE FUNCTION app_can_access_client(cid uuid) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT EXISTS (SELECT 1 FROM clients c WHERE c.id = cid) $$;`,
  );
  // Trainer ↔ client assignment checks that must not go through RLS (the assignments policy itself
  // uses them, and clients' visibility depends on assignments).
  stmt(`CREATE OR REPLACE FUNCTION app_trainer_assigned(cid uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
    SELECT EXISTS (SELECT 1 FROM trainer_client_assignments a
      WHERE a.client_id = cid AND a.trainer_id = app_trainer_id() AND a.ended_at IS NULL)
  $$;`);
  // A trainer may assign themselves only to a client they have just created (no active trainer yet).
  stmt(`CREATE OR REPLACE FUNCTION app_new_client_of_mine(cid uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
    SELECT EXISTS (SELECT 1 FROM clients c
      WHERE c.id = cid AND c.organization_id = app_org_id() AND c.created_by = app_user_id())
    AND NOT EXISTS (SELECT 1 FROM trainer_client_assignments a WHERE a.client_id = cid AND a.ended_at IS NULL)
  $$;`);
  for (const f of ['app_trainer_assigned(uuid)', 'app_new_client_of_mine(uuid)']) {
    stmt(`REVOKE ALL ON FUNCTION ${f} FROM PUBLIC;`);
    stmt(`GRANT EXECUTE ON FUNCTION ${f} TO app_runtime;`);
  }
  // Global e-mail uniqueness check that does not leak which organization uses it.
  stmt(
    `CREATE OR REPLACE FUNCTION email_in_use(e text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM users WHERE lower(email) = lower(e)) $$;`,
  );
  stmt(`REVOKE ALL ON FUNCTION email_in_use(text) FROM PUBLIC;`);
  stmt(`GRANT EXECUTE ON FUNCTION email_in_use(text) TO app_runtime;`);
  // Clients alert their assigned trainers (pain, substitution) without being able to write
  // arbitrary notifications: only for their own client record, only to its active trainers.
  stmt(`CREATE OR REPLACE FUNCTION notify_client_trainers(cid uuid, ntype text, ntitle text, nbody text, nlink text) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
  DECLARE n integer;
  BEGIN
    IF app_org_id() IS NULL OR NOT (app_client_id() = cid OR app_is_staff()) THEN
      RAISE EXCEPTION 'notify_client_trainers: not allowed' USING ERRCODE = '42501';
    END IF;
    INSERT INTO notifications (id, organization_id, user_id, channel, type, title, body, link)
    SELECT gen_random_uuid(), c.organization_id, tr.user_id, 'in_app', ntype, ntitle, nbody, nlink
    FROM clients c
    JOIN trainer_client_assignments a ON a.client_id = c.id AND a.ended_at IS NULL
    JOIN trainers tr ON tr.id = a.trainer_id
    WHERE c.id = cid AND c.organization_id = app_org_id();
    GET DIAGNOSTICS n = ROW_COUNT;
    RETURN n;
  END $$;`);
  stmt(`REVOKE ALL ON FUNCTION notify_client_trainers(uuid, text, text, text, text) FROM PUBLIC;`);
  stmt(
    `GRANT EXECUTE ON FUNCTION notify_client_trainers(uuid, text, text, text, text) TO app_runtime;`,
  );

  // Scope triggers.
  stmt(`CREATE OR REPLACE FUNCTION inherit_scope() RETURNS trigger LANGUAGE plpgsql AS $$
  DECLARE
    parent_id uuid := (to_jsonb(NEW) ->> TG_ARGV[1])::uuid;
    p_org uuid;
    p_client uuid;
  BEGIN
    IF TG_ARGV[0] = 'import_jobs' THEN
      EXECUTE format('SELECT organization_id, NULL::uuid FROM %I WHERE id = $1', TG_ARGV[0]) INTO p_org, p_client USING parent_id;
    ELSE
      EXECUTE format('SELECT organization_id, client_id FROM %I WHERE id = $1', TG_ARGV[0]) INTO p_org, p_client USING parent_id;
    END IF;
    IF p_org IS NULL THEN
      RAISE EXCEPTION 'inherit_scope: parent %.% not found', TG_ARGV[0], parent_id USING ERRCODE = 'foreign_key_violation';
    END IF;
    NEW.organization_id := p_org;
    IF TG_ARGV[0] <> 'import_jobs' THEN
      NEW.client_id := p_client;
    END IF;
    RETURN NEW;
  END $$;`);
  stmt(`CREATE OR REPLACE FUNCTION check_client_org() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
  BEGIN
    IF NEW.client_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM clients WHERE id = NEW.client_id AND organization_id = NEW.organization_id) THEN
      RAISE EXCEPTION 'client % does not belong to organization %', NEW.client_id, NEW.organization_id USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END $$;`);
  for (const [table, [parent, fk]] of Object.entries(INHERIT_SCOPE)) {
    stmt(
      `DROP TRIGGER IF EXISTS ${table}_inherit_scope ON ${table}; CREATE TRIGGER ${table}_inherit_scope BEFORE INSERT OR UPDATE ON ${table} FOR EACH ROW EXECUTE FUNCTION inherit_scope('${parent}', '${fk}');`,
    );
  }
  for (const table of CHECK_CLIENT_ORG) {
    stmt(
      `DROP TRIGGER IF EXISTS ${table}_check_client_org ON ${table}; CREATE TRIGGER ${table}_check_client_org BEFORE INSERT OR UPDATE ON ${table} FOR EACH ROW EXECUTE FUNCTION check_client_org();`,
    );
  }

  // A client may update their own record (contact details), but only the self-editable columns
  // (CLIENT_SELF_EDITABLE_FIELDS in the domain); the use case checks it too.
  stmt(`CREATE OR REPLACE FUNCTION clients_client_self_update() RETURNS trigger LANGUAGE plpgsql AS $$
  BEGIN
    IF app_has_role('CLIENT') AND NOT app_is_staff() AND
       (to_jsonb(NEW) - ARRAY['email','phone_enc','preferences','updated_at','updated_by','version'])
         IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['email','phone_enc','preferences','updated_at','updated_by','version']) THEN
      RAISE EXCEPTION 'permission denied: a client may only change email, phone and preferences'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
  END $$;`);
  stmt(
    `DROP TRIGGER IF EXISTS clients_client_self_update ON clients; CREATE TRIGGER clients_client_self_update BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION clients_client_self_update();`,
  );

  // Policies.
  for (const [table, p] of Object.entries(RLS_POLICIES)) {
    if (p.kind === 'global_readonly') {
      stmt(`GRANT SELECT ON ${table} TO app_runtime;`);
      continue;
    }
    stmt(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;`);
    stmt(`DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = '${table}' LOOP
    EXECUTE format('DROP POLICY %I ON ${table}', p.policyname);
  END LOOP;
END $$;`);
    if (p.kind === 'system_only') continue;
    stmt(`GRANT SELECT, INSERT, UPDATE, DELETE ON ${table} TO app_runtime;`);
    switch (p.kind) {
      case 'catalog':
        stmt(
          `CREATE POLICY ${table}_select ON ${table} FOR SELECT USING (organization_id IS NULL OR organization_id = app_org_id());`,
        );
        stmt(
          `CREATE POLICY ${table}_write ON ${table} FOR ALL USING (organization_id = app_org_id() AND app_is_staff()) WITH CHECK (organization_id = app_org_id() AND app_is_staff());`,
        );
        break;
      case 'catalog_child': {
        const vis = `EXISTS (SELECT 1 FROM ${p.parent} x WHERE x.id = ${table}.${p.fk})`;
        const own = `EXISTS (SELECT 1 FROM ${p.parent} x WHERE x.id = ${table}.${p.fk} AND x.organization_id = app_org_id()) AND app_is_staff()`;
        stmt(`CREATE POLICY ${table}_select ON ${table} FOR SELECT USING (${vis});`);
        stmt(
          `CREATE POLICY ${table}_write ON ${table} FOR ALL USING (${own}) WITH CHECK (${own});`,
        );
        break;
      }
      case 'client_child': {
        const write = p.clientWrite
          ? `app_can_access_client(client_id)`
          : `app_can_access_client(client_id) AND app_is_staff()`;
        stmt(
          `CREATE POLICY ${table}_select ON ${table} FOR SELECT USING (app_can_access_client(client_id));`,
        );
        stmt(
          `CREATE POLICY ${table}_write ON ${table} FOR ALL USING (${write}) WITH CHECK (${write});`,
        );
        break;
      }
      case 'client_owned':
      case 'client_optional': {
        // Same rule as app_can_access_client(), without re-entering the clients and assignments
        // policies for every row (Phase 14: 1 000 clients). Safe because the policy also requires
        // organization_id = app_org_id() and check_client_org/inherit_scope keep the row's client
        // in that organization.
        const byRole = `(app_has_role('ADMIN') OR (app_has_role('TRAINER') AND app_trainer_assigned(client_id)) OR (app_has_role('CLIENT') AND client_id = app_client_id()))`;
        const access =
          p.kind === 'client_owned'
            ? byRole
            : `(CASE WHEN client_id IS NULL THEN app_is_staff() ELSE ${byRole} END)`;
        const read = p.clientRead ? access : `${access} AND app_is_staff()`;
        const write = p.clientWrite ? access : `${access} AND app_is_staff()`;
        stmt(
          `CREATE POLICY ${table}_select ON ${table} FOR SELECT USING (organization_id = app_org_id() AND ${read});`,
        );
        stmt(
          `CREATE POLICY ${table}_write ON ${table} FOR ALL USING (organization_id = app_org_id() AND ${write}) WITH CHECK (organization_id = app_org_id() AND ${write});`,
        );
        break;
      }
      case 'custom':
        stmt(p.sql);
        break;
    }
  }
  // Append-only audit trail: no UPDATE/DELETE privilege for the runtime role either.
  stmt(`REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM app_runtime;`);
  stmt(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_runtime;`);

  return out.join('\n--> statement-breakpoint\n') + '\n';
}
